-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.alert_logs (
  id integer NOT NULL DEFAULT nextval('alert_logs_id_seq'::regclass),
  alert_id integer NOT NULL,
  action character varying NOT NULL,
  message text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT alert_logs_pkey PRIMARY KEY (id),
  CONSTRAINT alert_logs_alert_id_fkey FOREIGN KEY (alert_id) REFERENCES public.alerts(id)
);
CREATE TABLE public.alertas_consumo (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  insumo_id uuid NOT NULL,
  movimiento_id uuid NOT NULL,
  tipo_alerta text NOT NULL DEFAULT 'consumo_anomalo'::text,
  estado text NOT NULL DEFAULT 'pendiente'::text CHECK (estado = ANY (ARRAY['pendiente'::text, 'confirmada'::text, 'ignorada'::text])),
  mensaje text,
  fecha_creacion timestamp without time zone DEFAULT now(),
  fecha_atendida timestamp without time zone,
  CONSTRAINT alertas_consumo_pkey PRIMARY KEY (id),
  CONSTRAINT alertas_consumo_insumo_id_fkey FOREIGN KEY (insumo_id) REFERENCES public.insumos(id),
  CONSTRAINT alertas_consumo_movimiento_id_fkey FOREIGN KEY (movimiento_id) REFERENCES public.movimientos_inventario(id)
);
CREATE TABLE public.alertas_vencimiento (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  insumo_id uuid NOT NULL,
  dias_antes_vencimiento integer NOT NULL DEFAULT 7,
  notificacion_enviada boolean DEFAULT false,
  fecha_notificacion timestamp with time zone,
  fecha_creacion timestamp with time zone DEFAULT now(),
  CONSTRAINT alertas_vencimiento_pkey PRIMARY KEY (id)
);
CREATE TABLE public.alerts (
  id integer NOT NULL DEFAULT nextval('alerts_id_seq'::regclass),
  input_id integer NOT NULL,
  status character varying NOT NULL DEFAULT 'NEW'::character varying,
  current_value numeric,
  expected_average numeric,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  resolved_at timestamp without time zone,
  CONSTRAINT alerts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.asistencia (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL,
  turno_id uuid,
  fecha date NOT NULL,
  turno_inicio time without time zone,
  turno_fin time without time zone,
  entrada_real time without time zone,
  salida_real time without time zone,
  estado character varying NOT NULL CHECK (estado::text = ANY (ARRAY['a_tiempo'::character varying, 'tarde'::character varying, 'ausencia'::character varying, 'justificado'::character varying]::text[])),
  minutos_retraso integer DEFAULT 0,
  minutos_extra integer DEFAULT 0,
  observaciones text,
  ip_marcaje inet,
  dispositivo character varying,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT asistencia_pkey PRIMARY KEY (id),
  CONSTRAINT asistencia_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT asistencia_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id),
  CONSTRAINT asistencia_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT asistencia_turno_id_fkey FOREIGN KEY (turno_id) REFERENCES public.turnos(id)
);
CREATE TABLE public.bonos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  planilla_id uuid NOT NULL,
  concepto character varying NOT NULL,
  monto numeric NOT NULL,
  tipo character varying DEFAULT 'bono'::character varying CHECK (tipo::text = ANY (ARRAY['bono'::character varying, 'comision'::character varying, 'incentivo'::character varying, 'otro'::character varying]::text[])),
  aplicado_por uuid,
  fecha_aplicacion timestamp with time zone DEFAULT now(),
  observaciones text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  CONSTRAINT bonos_pkey PRIMARY KEY (id),
  CONSTRAINT bonos_planilla_id_fkey FOREIGN KEY (planilla_id) REFERENCES public.planillas(id),
  CONSTRAINT bonos_aplicado_por_fkey FOREIGN KEY (aplicado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.categorias_insumos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre character varying NOT NULL UNIQUE,
  descripcion text,
  color character varying DEFAULT '#f4b400'::character varying,
  icono character varying,
  activa boolean DEFAULT true,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT categorias_insumos_pkey PRIMARY KEY (id),
  CONSTRAINT categorias_insumos_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT categorias_insumos_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.categorias_productos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre character varying NOT NULL UNIQUE,
  descripcion text,
  color character varying DEFAULT '#3B82F6'::character varying,
  icono character varying,
  activa boolean DEFAULT true,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT categorias_productos_pkey PRIMARY KEY (id),
  CONSTRAINT categorias_productos_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT categorias_productos_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.categorias_recetas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre character varying NOT NULL UNIQUE,
  descripcion text,
  color character varying DEFAULT '#3B82F6'::character varying,
  icono character varying,
  activa boolean DEFAULT true,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT categorias_recetas_pkey PRIMARY KEY (id),
  CONSTRAINT categorias_recetas_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id),
  CONSTRAINT categorias_recetas_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.clientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre character varying NOT NULL,
  telefono character varying,
  email character varying,
  direccion text,
  tipo_cliente character varying DEFAULT 'Regular'::character varying CHECK (tipo_cliente::text = ANY (ARRAY['Regular'::character varying, 'Frecuente'::character varying, 'VIP'::character varying, 'Corporativo'::character varying]::text[])),
  fecha_registro timestamp with time zone DEFAULT now(),
  total_compras numeric DEFAULT 0.0,
  ultima_compra timestamp with time zone,
  activo boolean DEFAULT true,
  observaciones text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT clientes_pkey PRIMARY KEY (id),
  CONSTRAINT clientes_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT clientes_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.configuracion_aguinaldo (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  porcentaje numeric NOT NULL DEFAULT 8.33,
  dias_minimos integer DEFAULT 0,
  activa boolean DEFAULT true,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT configuracion_aguinaldo_pkey PRIMARY KEY (id),
  CONSTRAINT configuracion_aguinaldo_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT configuracion_aguinaldo_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.configuracion_deducciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  concepto character varying NOT NULL UNIQUE,
  porcentaje numeric,
  monto_fijo numeric,
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['legal'::character varying, 'opcional'::character varying, 'empresa'::character varying]::text[])),
  aplica_a character varying DEFAULT 'todos'::character varying CHECK (aplica_a::text = ANY (ARRAY['todos'::character varying, 'segun_tabla'::character varying, 'especifico'::character varying]::text[])),
  tabla_progresiva jsonb,
  activa boolean DEFAULT true,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT configuracion_deducciones_pkey PRIMARY KEY (id),
  CONSTRAINT configuracion_deducciones_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT configuracion_deducciones_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.deducciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  planilla_id uuid NOT NULL,
  concepto character varying NOT NULL,
  monto numeric NOT NULL,
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['legal'::character varying, 'personal'::character varying, 'prestamo'::character varying, 'otro'::character varying]::text[])),
  aplicado_por uuid,
  fecha_aplicacion timestamp with time zone DEFAULT now(),
  observaciones text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  CONSTRAINT deducciones_pkey PRIMARY KEY (id),
  CONSTRAINT deducciones_planilla_id_fkey FOREIGN KEY (planilla_id) REFERENCES public.planillas(id),
  CONSTRAINT deducciones_aplicado_por_fkey FOREIGN KEY (aplicado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.detalles_venta (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venta_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  cantidad integer NOT NULL,
  precio_unitario numeric NOT NULL,
  descuento numeric DEFAULT 0.0,
  subtotal numeric NOT NULL,
  observaciones text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  CONSTRAINT detalles_venta_pkey PRIMARY KEY (id),
  CONSTRAINT detalles_venta_venta_id_fkey FOREIGN KEY (venta_id) REFERENCES public.ventas(id),
  CONSTRAINT detalles_venta_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.productos(id)
);
CREATE TABLE public.evaluaciones_proveedores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proveedor_id uuid NOT NULL,
  usuario_id uuid NOT NULL,
  calificacion integer NOT NULL CHECK (calificacion >= 1 AND calificacion <= 5),
  criterios jsonb NOT NULL,
  comentarios text,
  fecha_evaluacion timestamp with time zone DEFAULT now(),
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  CONSTRAINT evaluaciones_proveedores_pkey PRIMARY KEY (id),
  CONSTRAINT evaluaciones_proveedores_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id),
  CONSTRAINT evaluaciones_proveedores_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.franjas_requeridas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dia_semana character varying NOT NULL CHECK (dia_semana::text = ANY (ARRAY['lunes'::character varying, 'martes'::character varying, 'miercoles'::character varying, 'jueves'::character varying, 'viernes'::character varying, 'sabado'::character varying, 'domingo'::character varying]::text[])),
  hora_inicio time without time zone NOT NULL,
  hora_fin time without time zone NOT NULL,
  area character varying NOT NULL CHECK (area::text = ANY (ARRAY['cocina'::character varying, 'servicio'::character varying, 'caja'::character varying, 'limpieza'::character varying, 'administracion'::character varying]::text[])),
  min_empleados integer NOT NULL DEFAULT 1,
  activo boolean DEFAULT true,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  CONSTRAINT franjas_requeridas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.historial_pagos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL,
  planilla_id uuid,
  periodo character varying NOT NULL,
  fecha_pago date NOT NULL,
  monto_pagado numeric NOT NULL,
  tipo_pago character varying NOT NULL CHECK (tipo_pago::text = ANY (ARRAY['regular'::character varying, 'aguinaldo'::character varying, 'liquidacion'::character varying, 'adelanto'::character varying]::text[])),
  metodo_pago character varying DEFAULT 'transferencia'::character varying CHECK (metodo_pago::text = ANY (ARRAY['transferencia'::character varying, 'efectivo'::character varying, 'cheque'::character varying]::text[])),
  estado character varying DEFAULT 'pagado'::character varying CHECK (estado::text = ANY (ARRAY['pagado'::character varying, 'pendiente'::character varying, 'cancelado'::character varying]::text[])),
  numero_comprobante character varying,
  observaciones text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  procesado_por uuid,
  CONSTRAINT historial_pagos_pkey PRIMARY KEY (id),
  CONSTRAINT historial_pagos_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT historial_pagos_planilla_id_fkey FOREIGN KEY (planilla_id) REFERENCES public.planillas(id),
  CONSTRAINT historial_pagos_procesado_por_fkey FOREIGN KEY (procesado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.historial_salarios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL,
  salario_anterior numeric,
  salario_nuevo numeric,
  tarifa_hora_anterior numeric,
  tarifa_hora_nueva numeric,
  tipo_contrato_anterior character varying,
  tipo_contrato_nuevo character varying,
  motivo text,
  cambiado_por uuid,
  fecha_cambio timestamp with time zone DEFAULT now(),
  CONSTRAINT historial_salarios_pkey PRIMARY KEY (id),
  CONSTRAINT historial_salarios_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT historial_salarios_cambiado_por_fkey FOREIGN KEY (cambiado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.horarios_local (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dia_semana character varying NOT NULL CHECK (dia_semana::text = ANY (ARRAY['lunes'::character varying, 'martes'::character varying, 'miercoles'::character varying, 'jueves'::character varying, 'viernes'::character varying, 'sabado'::character varying, 'domingo'::character varying]::text[])),
  abierto boolean DEFAULT true,
  hora_apertura time without time zone,
  hora_cierre time without time zone,
  activo boolean DEFAULT true,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  CONSTRAINT horarios_local_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ingredientes_receta (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  receta_id uuid NOT NULL,
  insumo_id uuid NOT NULL,
  cantidad numeric NOT NULL,
  unidad_medida character varying NOT NULL,
  costo_unitario numeric DEFAULT 0.0,
  costo_total numeric DEFAULT 0.0,
  observaciones text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  CONSTRAINT ingredientes_receta_pkey PRIMARY KEY (id),
  CONSTRAINT ingredientes_receta_receta_id_fkey FOREIGN KEY (receta_id) REFERENCES public.recetas(id),
  CONSTRAINT ingredientes_receta_insumo_id_fkey FOREIGN KEY (insumo_id) REFERENCES public.insumos(id)
);
CREATE TABLE public.insumos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo character varying NOT NULL UNIQUE,
  nombre character varying NOT NULL,
  descripcion text,
  unidad_medida character varying NOT NULL,
  stock_minimo numeric DEFAULT 0,
  stock_maximo numeric,
  proveedor_principal_id uuid,
  estado character varying DEFAULT 'Activo'::character varying,
  observaciones text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT insumos_pkey PRIMARY KEY (id),
  CONSTRAINT insumos_proveedor_principal_fkey FOREIGN KEY (proveedor_principal_id) REFERENCES public.proveedores(id),
  CONSTRAINT insumos_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT insumos_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.insumos_categorias (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  insumo_id uuid NOT NULL,
  categoria_id uuid NOT NULL,
  fecha_asignacion timestamp with time zone DEFAULT now(),
  activa boolean DEFAULT true,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT insumos_categorias_pkey PRIMARY KEY (id),
  CONSTRAINT insumos_categorias_insumo_fkey FOREIGN KEY (insumo_id) REFERENCES public.insumos(id),
  CONSTRAINT insumos_categorias_categoria_fkey FOREIGN KEY (categoria_id) REFERENCES public.categorias_insumos(id),
  CONSTRAINT insumos_categorias_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT insumos_categorias_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.lotes_insumos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  insumo_id uuid NOT NULL,
  lote character varying NOT NULL,
  cantidad_inicial numeric NOT NULL,
  cantidad_actual numeric NOT NULL,
  precio_unitario numeric NOT NULL,
  proveedor_id uuid,
  fecha_ingreso date NOT NULL DEFAULT CURRENT_DATE,
  fecha_vencimiento date,
  estado character varying DEFAULT 'Activo'::character varying,
  observaciones text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT lotes_insumos_pkey PRIMARY KEY (id),
  CONSTRAINT lotes_insumos_insumo_fkey FOREIGN KEY (insumo_id) REFERENCES public.insumos(id),
  CONSTRAINT lotes_insumos_proveedor_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id),
  CONSTRAINT lotes_insumos_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT lotes_insumos_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.metricas_dashboard (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre character varying NOT NULL,
  valor numeric NOT NULL,
  unidad character varying,
  tipo_metrica character varying NOT NULL CHECK (tipo_metrica::text = ANY (ARRAY['ventas'::character varying, 'inventario'::character varying, 'personal'::character varying, 'financiero'::character varying, 'operacional'::character varying]::text[])),
  periodo character varying NOT NULL,
  fecha_medicion date NOT NULL,
  comparacion_anterior numeric,
  porcentaje_cambio numeric,
  tendencia character varying CHECK (tendencia::text = ANY (ARRAY['ascendente'::character varying, 'descendente'::character varying, 'estable'::character varying]::text[])),
  meta numeric,
  cumplimiento_meta numeric,
  activa boolean DEFAULT true,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT metricas_dashboard_pkey PRIMARY KEY (id),
  CONSTRAINT metricas_dashboard_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT metricas_dashboard_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.movimientos_inventario (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lote_id uuid NOT NULL,
  tipo character varying NOT NULL,
  cantidad numeric NOT NULL,
  motivo character varying NOT NULL,
  documento character varying,
  lote_origen_id uuid,
  lote_destino_id uuid,
  costo_unitario numeric,
  costo_total numeric,
  usuario_id uuid NOT NULL,
  fecha_movimiento timestamp with time zone DEFAULT now(),
  observaciones text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  venta_id uuid,
  CONSTRAINT movimientos_inventario_pkey PRIMARY KEY (id),
  CONSTRAINT movimientos_inventario_lote_fkey FOREIGN KEY (lote_id) REFERENCES public.lotes_insumos(id),
  CONSTRAINT movimientos_inventario_lote_origen_fkey FOREIGN KEY (lote_origen_id) REFERENCES public.lotes_insumos(id),
  CONSTRAINT movimientos_inventario_lote_destino_fkey FOREIGN KEY (lote_destino_id) REFERENCES public.lotes_insumos(id),
  CONSTRAINT movimientos_inventario_usuario_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT movimientos_inventario_venta_id_fkey FOREIGN KEY (venta_id) REFERENCES public.ventas(id)
);
CREATE TABLE public.operaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre character varying NOT NULL UNIQUE CHECK (nombre::text = ANY (ARRAY['crear'::character varying, 'leer'::character varying, 'editar'::character varying, 'eliminar'::character varying]::text[])),
  fecha_creacion timestamp with time zone DEFAULT now(),
  CONSTRAINT operaciones_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pasos_receta (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  receta_id uuid NOT NULL,
  numero_paso integer NOT NULL,
  descripcion text NOT NULL,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  CONSTRAINT pasos_receta_pkey PRIMARY KEY (id),
  CONSTRAINT pasos_receta_receta_id_fkey FOREIGN KEY (receta_id) REFERENCES public.recetas(id)
);
CREATE TABLE public.planillas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL,
  periodo character varying NOT NULL,
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  estado character varying DEFAULT 'pendiente'::character varying CHECK (estado::text = ANY (ARRAY['pendiente'::character varying, 'calculada'::character varying, 'pagada'::character varying, 'cancelada'::character varying]::text[])),
  horas_programadas numeric DEFAULT 0,
  horas_trabajadas numeric,
  horas_ausencia numeric DEFAULT 0,
  horas_extra numeric DEFAULT 0,
  dias_trabajados integer,
  dias_ausencias integer DEFAULT 0,
  salario_base numeric,
  monto_horas_extra numeric DEFAULT 0,
  salario_bruto numeric,
  total_bonos numeric DEFAULT 0,
  total_deducciones numeric DEFAULT 0,
  salario_neto numeric,
  fecha_calculo timestamp with time zone,
  calculado_por uuid,
  fecha_pago date,
  recibo_generado boolean DEFAULT false,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT planillas_pkey PRIMARY KEY (id),
  CONSTRAINT planillas_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT planillas_calculado_por_fkey FOREIGN KEY (calculado_por) REFERENCES public.usuarios(id),
  CONSTRAINT planillas_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT planillas_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.predicciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tipo_prediccion character varying NOT NULL CHECK (tipo_prediccion::text = ANY (ARRAY['demanda_insumos'::character varying, 'ventas_productos'::character varying, 'ingresos'::character varying, 'asistencia_personal'::character varying]::text[])),
  periodo character varying NOT NULL,
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  insumo_id uuid,
  producto_id uuid,
  valor_predicho numeric NOT NULL,
  valor_real numeric,
  desviacion numeric,
  porcentaje_desviacion numeric,
  nivel_confianza numeric DEFAULT 0.0,
  algoritmo character varying,
  parametros jsonb,
  activa boolean DEFAULT true,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT predicciones_pkey PRIMARY KEY (id),
  CONSTRAINT predicciones_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.productos(id),
  CONSTRAINT predicciones_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT predicciones_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id),
  CONSTRAINT predicciones_insumo_id_fkey FOREIGN KEY (insumo_id) REFERENCES public.insumos(id)
);
CREATE TABLE public.predicciones_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fecha_ejecucion timestamp with time zone DEFAULT now(),
  tipo_ejecucion character varying NOT NULL,
  predicciones_generadas integer DEFAULT 0,
  desviaciones_actualizadas integer DEFAULT 0,
  estado character varying NOT NULL,
  mensaje text,
  tiempo_ejecucion interval,
  ejecutado_por uuid,
  CONSTRAINT predicciones_log_pkey PRIMARY KEY (id),
  CONSTRAINT predicciones_log_ejecutado_por_fkey FOREIGN KEY (ejecutado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.productos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo character varying NOT NULL UNIQUE,
  nombre text NOT NULL,
  descripcion text,
  categoria_id uuid NOT NULL,
  precio_venta numeric NOT NULL,
  costo_total numeric DEFAULT 0.0,
  margen_ganancia numeric DEFAULT 0.0,
  ventas_registradas integer DEFAULT 0,
  ultima_venta timestamp with time zone,
  activo boolean DEFAULT true,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT productos_pkey PRIMARY KEY (id),
  CONSTRAINT productos_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.categorias_productos(id),
  CONSTRAINT productos_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT productos_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.proveedores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo character varying NOT NULL UNIQUE,
  nombre character varying NOT NULL,
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['Carnes y Embutidos'::character varying, 'Frutas y Verduras'::character varying, 'Lácteos y Derivados'::character varying, 'Granos y Harinas'::character varying, 'Condimentos y Especias'::character varying, 'Bebidas'::character varying, 'Otros'::character varying]::text[])),
  telefono character varying,
  email character varying,
  direccion text,
  contacto_principal character varying,
  rtn character varying,
  estado character varying DEFAULT 'Activo'::character varying CHECK (estado::text = ANY (ARRAY['Activo'::character varying, 'Inactivo'::character varying, 'Suspendido'::character varying]::text[])),
  calificacion_promedio numeric DEFAULT 0.0,
  total_compras numeric DEFAULT 0.0,
  ultima_compra date,
  observaciones text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT proveedores_pkey PRIMARY KEY (id),
  CONSTRAINT proveedores_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT proveedores_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.recetas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo character varying NOT NULL UNIQUE,
  nombre character varying NOT NULL,
  descripcion text,
  categoria_id uuid NOT NULL,
  tiempo_preparacion integer NOT NULL,
  rendimiento integer NOT NULL,
  nivel_dificultad character varying DEFAULT 'Intermedio'::character varying CHECK (nivel_dificultad::text = ANY (ARRAY['Fácil'::character varying, 'Intermedio'::character varying, 'Difícil'::character varying]::text[])),
  instrucciones text NOT NULL,
  costo_total numeric DEFAULT 0.0,
  precio_sugerido numeric DEFAULT 0.0,
  margen_ganancia numeric DEFAULT 0.0,
  popularidad integer DEFAULT 0,
  rentabilidad numeric DEFAULT 0.0,
  veces_preparada integer DEFAULT 0,
  activa boolean DEFAULT true,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT recetas_pkey PRIMARY KEY (id),
  CONSTRAINT recetas_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.categorias_recetas(id),
  CONSTRAINT recetas_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT recetas_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.recetas_producto (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  producto_id uuid NOT NULL,
  receta_id uuid NOT NULL,
  cantidad integer NOT NULL DEFAULT 1,
  observaciones text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  CONSTRAINT recetas_producto_pkey PRIMARY KEY (id),
  CONSTRAINT recetas_producto_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.productos(id),
  CONSTRAINT recetas_producto_receta_id_fkey FOREIGN KEY (receta_id) REFERENCES public.recetas(id)
);
CREATE TABLE public.recibos_pago (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  planilla_id uuid NOT NULL,
  numero_recibo character varying NOT NULL UNIQUE,
  fecha_generacion timestamp with time zone DEFAULT now(),
  archivo_pdf text,
  estado character varying DEFAULT 'generado'::character varying CHECK (estado::text = ANY (ARRAY['generado'::character varying, 'enviado'::character varying, 'descargado'::character varying]::text[])),
  fecha_envio timestamp with time zone,
  fecha_descarga timestamp with time zone,
  generado_por uuid,
  observaciones text,
  CONSTRAINT recibos_pago_pkey PRIMARY KEY (id),
  CONSTRAINT recibos_pago_planilla_id_fkey FOREIGN KEY (planilla_id) REFERENCES public.planillas(id),
  CONSTRAINT recibos_pago_generado_por_fkey FOREIGN KEY (generado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre character varying NOT NULL UNIQUE,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.roles_vistas_operaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rol_id uuid NOT NULL,
  vista_id uuid NOT NULL,
  operacion_id uuid NOT NULL,
  fecha_asignacion timestamp with time zone DEFAULT now(),
  CONSTRAINT roles_vistas_operaciones_pkey PRIMARY KEY (id),
  CONSTRAINT roles_vistas_operaciones_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES public.roles(id),
  CONSTRAINT roles_vistas_operaciones_vista_id_fkey FOREIGN KEY (vista_id) REFERENCES public.vistas(id),
  CONSTRAINT roles_vistas_operaciones_operacion_id_fkey FOREIGN KEY (operacion_id) REFERENCES public.operaciones(id)
);
CREATE TABLE public.tipos_contrato (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre character varying NOT NULL UNIQUE,
  descripcion text,
  horas_semanales integer NOT NULL DEFAULT 40,
  tipo_salario character varying NOT NULL CHECK (tipo_salario::text = ANY (ARRAY['fijo'::character varying, 'por_hora'::character varying]::text[])),
  deduccion_seguro_social numeric DEFAULT 9.34,
  deduccion_impuesto character varying DEFAULT 'progresivo'::character varying CHECK (deduccion_impuesto::text = ANY (ARRAY['progresivo'::character varying, 'simplificado'::character varying]::text[])),
  horas_extra_aplicable boolean DEFAULT true,
  tarifa_horas_extra numeric DEFAULT 1.5,
  aguinaldo_completo boolean DEFAULT true,
  activo boolean DEFAULT true,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  CONSTRAINT tipos_contrato_pkey PRIMARY KEY (id)
);
CREATE TABLE public.turno_series (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL,
  descripcion text,
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  dias_semana jsonb,
  hora_inicio time without time zone NOT NULL,
  hora_fin time without time zone NOT NULL,
  area character varying NOT NULL,
  posicion character varying,
  creado_por uuid,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  CONSTRAINT turno_series_pkey PRIMARY KEY (id),
  CONSTRAINT turno_series_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT turno_series_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.turnos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL,
  fecha date NOT NULL,
  hora_inicio time without time zone NOT NULL,
  hora_fin time without time zone NOT NULL,
  area character varying NOT NULL CHECK (area::text = ANY (ARRAY['cocina'::character varying, 'servicio'::character varying, 'caja'::character varying, 'limpieza'::character varying, 'administracion'::character varying]::text[])),
  posicion character varying,
  estado character varying DEFAULT 'programado'::character varying CHECK (estado::text = ANY (ARRAY['programado'::character varying, 'confirmado'::character varying, 'cancelado'::character varying, 'completado'::character varying]::text[])),
  notas text,
  horas_trabajadas numeric,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  serie_id uuid,
  CONSTRAINT turnos_pkey PRIMARY KEY (id),
  CONSTRAINT turnos_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT turnos_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT turnos_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id),
  CONSTRAINT turnos_serie_id_fkey FOREIGN KEY (serie_id) REFERENCES public.turno_series(id)
);
CREATE TABLE public.usuarios (
  id uuid NOT NULL,
  nombre character varying NOT NULL,
  apellido character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  telefono character varying,
  rol_id uuid,
  departamento character varying NOT NULL,
  estado character varying DEFAULT 'Activo'::character varying CHECK (estado::text = ANY (ARRAY['Activo'::character varying, 'Inactivo'::character varying]::text[])),
  biografia text,
  foto_perfil text,
  ultimo_acceso timestamp with time zone,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  creado_por uuid,
  modificado_por uuid,
  notas text,
  cedula character varying UNIQUE,
  puesto character varying,
  fecha_ingreso date,
  horas_semanales integer DEFAULT 40,
  disponibilidad jsonb,
  salario_base numeric,
  tarifa_hora numeric,
  tipo_contrato character varying,
  cuenta_banco character varying,
  CONSTRAINT usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT usuarios_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT usuarios_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id),
  CONSTRAINT usuarios_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT usuarios_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES public.roles(id)
);
CREATE TABLE public.ventas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  numero_orden character varying NOT NULL UNIQUE,
  cliente_id uuid,
  cliente_nombre character varying,
  cliente_telefono character varying,
  tipo_venta character varying NOT NULL CHECK (tipo_venta::text = ANY (ARRAY['Local'::character varying, 'Para Llevar'::character varying, 'Domicilio'::character varying]::text[])),
  estado character varying NOT NULL DEFAULT 'Pendiente'::character varying CHECK (estado::text = ANY (ARRAY['Pendiente'::character varying, 'En Proceso'::character varying, 'Completada'::character varying, 'Cancelada'::character varying]::text[])),
  metodo_pago character varying NOT NULL CHECK (metodo_pago::text = ANY (ARRAY['Efectivo'::character varying, 'Tarjeta'::character varying, 'Transferencia'::character varying]::text[])),
  subtotal numeric NOT NULL DEFAULT 0.0,
  descuento numeric DEFAULT 0.0,
  impuestos numeric DEFAULT 0.0,
  total numeric NOT NULL DEFAULT 0.0,
  fecha_venta timestamp with time zone DEFAULT now(),
  fecha_entrega timestamp with time zone,
  direccion_entrega text,
  observaciones text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  fecha_modificacion timestamp with time zone DEFAULT now(),
  vendedor_id uuid,
  creado_por uuid,
  modificado_por uuid,
  CONSTRAINT ventas_pkey PRIMARY KEY (id),
  CONSTRAINT ventas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT ventas_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.usuarios(id),
  CONSTRAINT ventas_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id),
  CONSTRAINT ventas_modificado_por_fkey FOREIGN KEY (modificado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.vistas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ruta character varying NOT NULL UNIQUE,
  fecha_creacion timestamp with time zone DEFAULT now(),
  CONSTRAINT vistas_pkey PRIMARY KEY (id)
);